### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by tfjmp** [arthurscchan/ProvMark#7] opened 2017-11-23 17:59 UTC
On commit d5a32d67caff6ccc9fa38cd1712e11dfb15bfa87 I get the following error:

```
./fullAutomation.py cam /tmp ./benchmarkProgram/control ./benchmarkProgram/cmdCreat 2 ./result.clingo
Starting stage 1...Generating provenance from native tools
Control
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/startTool/startCamflow.py", line 69, in <module>
    startCamflow(stagePath, workingPath, '%s-%d' % (suffix, i))
  File "/home/vagrant/workspace/ProvMark/startTool/startCamflow.py", line 36, in startCamflow
    m = Merger({},result,next(file).rstrip(),DictMergerOps.FALLBACK_KEEP_HEAD,UnifierOps.KEEP_UPDATE_AND_HEAD_ENTITIES_HEAD_FIRST)
StopIteration
End Control
Program
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/startTool/startCamflow.py", line 69, in <module>
    startCamflow(stagePath, workingPath, '%s-%d' % (suffix, i))
  File "/home/vagrant/workspace/ProvMark/startTool/startCamflow.py", line 36, in startCamflow
    m = Merger({},result,next(file).rstrip(),DictMergerOps.FALLBACK_KEEP_HEAD,UnifierOps.KEEP_UPDATE_AND_HEAD_ENTITIES_HEAD_FIRST)
StopIteration
End Program
End of stage 1

Starting stage 2...Transforming provenance result to Clingo graph
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/genClingoGraph/provJson2Clingo.py", line 49, in <module>
    file = open(jsonFile, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output.provjson-control-1'
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/genClingoGraph/provJson2Clingo.py", line 49, in <module>
    file = open(jsonFile, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output.provjson-control-2'
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/genClingoGraph/provJson2Clingo.py", line 49, in <module>
    file = open(jsonFile, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output.provjson-program-1'
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/genClingoGraph/provJson2Clingo.py", line 49, in <module>
    file = open(jsonFile, "r")
FileNotFoundError: [Errno 2] No such file or directory: 'output.provjson-program-2'
End of stage 2

Starting stage 3...Generalizing graph from multiple trial
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/processGraph/generalizeGraph.py", line 26, in <module>
    graph2Node, graph2Edge, graph1Props, graph2Props, map = processGraph(sys.argv[i], sys.argv[i+1], clingoCode)
  File "/home/vagrant/workspace/ProvMark/processGraph/clingoFunction.py", line 117, in processGraph
    file = open(graph1Path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/workspace/ProvMark/working/clingo-control-1'
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/processGraph/generalizeGraph.py", line 26, in <module>
    graph2Node, graph2Edge, graph1Props, graph2Props, map = processGraph(sys.argv[i], sys.argv[i+1], clingoCode)
  File "/home/vagrant/workspace/ProvMark/processGraph/clingoFunction.py", line 117, in processGraph
    file = open(graph1Path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: '/home/vagrant/workspace/ProvMark/working/clingo-program-1'
End of stage 3

Starting stage 4...Generating benchmark
Traceback (most recent call last):
  File "/home/vagrant/workspace/ProvMark/processGraph/findSubgraph.py", line 24, in <module>
    graph2Node, graph2Edge, graph1Props, graph2Props, map = processGraph(sys.argv[4], sys.argv[5], clingoCode)
  File "/home/vagrant/workspace/ProvMark/processGraph/clingoFunction.py", line 117, in processGraph
    file = open(graph1Path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'general.clingo-control'
End of stage 4
```

**Comment by jamescheney** [comment] 2017-11-23 19:23
At a guess, the second parameter (/tmp) looks fishy.  That is supposed to be the root directory of the tool being used, e.g. for SPADE it is /home/vagrant/SPADE. Perhaps for camflow this doesn't matter if the binaries are globally visible?

It's also hard to tell what the problem is because the first two error messages aren't very specific.  The rest are just cascades because the outputs of the first step weren't created and so on.

I'll try to replicate using the CamFlow RPM Vagrantfile.

**Comment by jamescheney** [comment] 2017-11-24 20:56
I'm able to (sometimes) see successful completion using the Vagrantfile (as of  bd6beef ), but this seems somewhat nondeterministic, possibly because of #8.  Can you confirm that installing glibc-static solves the above problem on the vagrant/rpm vm?  I will try the commands you recommended using in #8.

**Comment by jamescheney** [comment] 2017-11-25 16:05
The StopIteration errors seem to be due to the strange code around this loop:

https://github.com/arthurscchan/ProvMark/blob/bd6beef669ace88f7922a7e6f6bce3c299dc41a3/startTool/startCamflow.py#L35

```
file = open('%s/temp.log' % workingPath, 'r')
	next(file)
	result={}

	for line in file:
		m = Merger({},result,next(file).rstrip(),DictMergerOps.FALLBACK_KEEP_HEAD,UnifierOps.KEEP_UPDATE_AND_HEAD_ENTITIES_HEAD_FIRST)
		m.merge()
		result = m.merged_root
file.close()
```
This appears to be trying to merge all of the json statements in the log into one.  But for reasons I'm not sure of, we call next(file) before the loop to skip over the first element of the file, then we do a for loop to iterate over the file, then inside the loop we use next(file) again to get the next line.  I'm not sure why we are doing this instead of just using the variable "line"; it looks to me like this might result in skipping half of the lines and raise a StopIteration error if there is an even number of lines.

**Comment by arthurscchan** [comment] 2017-11-26 18:00
I think I can guess the problem. Maybe @jamescheney  is right in other thread that this does cause race condition. The error is because the iteration cannot find additional line to loop for the merger. That's mean the resulting file is empty which is due to the data not yet flushed to the resulting file before camflow is forcefully stopped. This may show somethings related to race condition that I have been overlooking. I will try to fix it in due time. Sorry for that.

**Comment by jamescheney** [comment] 2017-11-28 12:48
This commit 2e6a543 seems to fix the immediate "StopIteration" problem.  I still get merge conflict errors, however.  I suggest we close this issue and make a new one for the new problem.

**Comment by jamescheney** [comment] 2018-02-04 19:47
This seems to be fixed now, closing.

**Closed as completed by jamescheney** 2018-02-04 19:47 UTC
